version: '3'

services:
  neo4j:
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./conf:/conf
      - ./data:/data
      - ./import:/import
      - ./logs:/logs
      - ./plugins:/plugins
    environment:
      NEO4J_AUTH: neo4j/test
      NEO4J_dbms_logs_debug_level: DEBUG

  # api:
  #   build: ./api
  #   ports:
  #     - 4001:4001
  #   environment:
  #     - NEO4J_URI=bolt://neo4j:7687
  #     - NEO4J_USER=neo4j
  #     - NEO4J_PASSWORD=letmein
  #     - GRAPHQL_LISTEN_PORT=4001
  #     - GRAPHQL_URI=http://api:4001/graphql

  #   links:
  #     - neo4j
  #   depends_on:
  #     - neo4j

  # ui:
  #   build: ./web-react
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - CI=true
  #     - REACT_APP_GRAPHQL_URI=/graphql
  #     - PROXY=http://api:4001/graphql
  #   links:
  #     - api
  #   depends_on:
  #     - api
